version: '3.8'

services:
  frontend:
    build:
      context: ./only-sams-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./only-sams-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./only-sams-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./only-sams-backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb+srv://samueljperry1991:b_%25nH9m4xSfZJqB@only-sams-db.6wz2wrk.mongodb.net/gameReviews?retryWrites=true&w=majority&appName=only-sams-db
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
